### ISSUE TITLE
Update Dx to HCC Mappings for 2021, 2022, 2023

### ISSUE THREAD

**Issue by dr00b** [yubin-park/hccpy#37]
Each year, CMS releases updated dx to HCC mappings as the diagnosis code-set evolves. The the files used in hccpy are copied directly from the public SAS models posted by CMS [here](https://www.cms.gov/Medicare/Health-Plans/MedicareAdvtgSpecRateStats/Risk-Adjustors). The SAS models are named like so: "2021 Midyear-Final-Model Software.zip".

In hccpy, the mappings from the SAS models are copied to the data dir. The "AllYearsCombined" mapping is a dedup'd combination of all the annual codesets released for a given model version. Below are examples for V24...
[F2421P1M.TXT](https://github.com/yubin-park/hccpy/blob/master/hccpy/data/F2421P1M.TXT)
[F2421P2M.TXT](https://github.com/yubin-park/hccpy/blob/master/hccpy/data/F2421P2M.TXT)
[F24_AllYearsCombined.TXT](https://github.com/yubin-park/hccpy/blob/master/hccpy/data/F24_AllYearsCombined.TXT)

**Tasks:**
- [x] Update 2021 V22 and V24 mappings to the finalized mappings.
- [x] Update 2022 V22 and V24 mappings to the finalized mappings.
- [ ] Update 2023 V22 and V24 mappings to use preliminary mappings.
- [x] Make sure the "AllYearsCombined" mappings are updated. The function utils.combine_dx2cc can help with this.
- [x] Update hccpy.HCCEngine.fnmaps to include any new files

**Comment by MasonRoberts** [comment]
I'm going to take a stab at this - thanks for the help David!

**Comment by dr00b** [comment]
Closed by #39

**Comment by helfa012** [comment]
There's still a task left to do!
